development:
  sessions:
    default:
      database: push_to_device_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: push_to_device_test
      hosts:
        - localhost:27017

staging:
  sessions:
    default:
      database: push_to_device_stg
      hosts:
        - 10.0.20.242:27017

production:
  sessions:
    default:
      database: push_to_device_prod
      hosts:
        - 10.0.10.239:27017
        - 10.0.11.206:27017
        - 10.0.10.85:27017
      options:
        consistency: :strong
